
###
POST http://{{default_url}}/update/gauge/gaugename/2.87
Content-Type: text/plain

###
POST http://{{default_url}}/update/counter/countername/23
Content-Type: text/plain

###
GET http://{{default_url}}/value/gauge/gaugename
Content-Type: text/plain

###
GET http://{{default_url}}/value/counter/countername
Content-Type: text/plain

###
POST http://{{default_url}}/update
Content-Type: application/json

{"id": "counterNameJSON",
  "type": "counter",
  "delta": 13}

###
POST http://{{default_url}}/update
Content-Type: application/json

{"id": "gaugeNameJSON",
  "type": "gauge",
  "value": 38.988}

###
POST http://{{default_url}}/value
Content-Type: application/json

{"id": "counterNameJSON",
  "type": "counter"}

###
POST http://{{default_url}}/valuedfdf
Content-Type: application/json

{"id": "gaugeNameJSON",
  "type": "gauge"}

###

GET http://{{default_url}}/


### With encoding
###
POST http://{{default_url}}/update
Content-Type: application/json
Accept-Encoding: gzip

{"id": "counterNameJSON",
  "type": "counter",
  "delta": 13}

###
POST http://{{default_url}}/update
Content-Type: application/json
Accept-Encoding: gzip

{"id": "gaugeNameJSON",
  "type": "gauge",
  "value": 38.988}

###
POST http://{{default_url}}/value
Content-Type: application/json
Accept-Encoding: gzip

{"id": "counterNameJSON",
  "type": "counter"}


###

GET http://{{default_url}}/
Accept-Encoding: gzip
Content-Type: text/html


###
POST http://{{default_url}}/value
Content-Type: application/json
Accept-Encoding: gzip

{"id": "gaugeNameJSON",
  "type": "gauge",
  "value": 38.988}

###
POST http://{{default_url}}/updates/
Content-Type: application/json
Accept-Encoding: gzip

[{"id":"gaugeNameBatchJSON","type":"gauge","value":138.988},
  {"id":"counterNameBatchJSON","type":"counter","delta":113}]


###
#bad hash
POST http://{{default_url}}/updates/
Content-Type: application/json
Accept-Encoding: gzip
HashSHA256: "fsklj325u2tiofiucvpwsjfl234"

[{"id":"gaugeNameBatchJSON","type":"gauge","value":138.988},
  {"id":"counterNameBatchJSON","type":"counter","delta":113}]


###
#good hash
POST http://{{default_url}}/updates/
Content-Type: application/json
Accept-Encoding: gzip
HashSHA256: "810f6b94525bcfac28f9870a314fdc151bdb6427bd0acdb6574100a98643945a"

[{"id":"gaugeNameBatchJSON","type":"gauge","value":138.988},
  {"id":"counterNameBatchJSON","type":"counter","delta":113}]