package main

import (
	"golang.org/x/tools/go/analysis/multichecker"
)

func main() {
	multichecker.Main(
		//asmdecl.Analyzer,
		//assign.Analyzer,
		//atomic.Analyzer,
		//atomicalign.Analyzer,
		//bools.Analyzer,
		//buildssa.Analyzer,
		//buildtag.Analyzer,
		//cgocall.Analyzer,
		//composite.Analyzer,
		//copylock.Analyzer,
		//ctrlflow.Analyzer,
		//deepequalerrors.Analyzer,
		//defers.Analyzer,
		//directive.Analyzer,
		//errorsas.Analyzer,
		//fieldalignment.Analyzer,
		//findcall.Analyzer,
		//framepointer.Analyzer,
		//httpresponse.Analyzer,
		//ifaceassert.Analyzer,
		//inspect.Analyzer,
		//loopclosure.Analyzer,
		//lostcancel.Analyzer,
		//nilfunc.Analyzer,
		//nilness.Analyzer,
		//pkgfact.Analyzer,
		//printf.Analyzer,
		//reflectvaluecompare.Analyzer,
		//shadow.Analyzer,
		//shift.Analyzer,
		//sigchanyzer.Analyzer,
		//slog.Analyzer,
		//sortslice.Analyzer,
		//stdmethods.Analyzer,
		//stringintconv.Analyzer,
		//structtag.Analyzer,
		//testinggoroutine.Analyzer,
		//tests.Analyzer,
		//timeformat.Analyzer,
		//unmarshal.Analyzer,
		//unreachable.Analyzer,
		//unsafeptr.Analyzer,
		//unusedresult.Analyzer,
		//unusedwrite.Analyzer,
		//usesgenerics.Analyzer,
		ExplicitExitAnalyzer,
	)
}
